CREATE TABLE `email_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`threadId` int NOT NULL,
	`gmailMessageId` varchar(255) NOT NULL,
	`gmailThreadId` varchar(255) NOT NULL,
	`from` varchar(500) NOT NULL,
	`to` text NOT NULL,
	`cc` text,
	`bcc` text,
	`subject` text,
	`bodyText` text,
	`bodyHtml` text,
	`snippet` text,
	`date` timestamp NOT NULL,
	`labels` json,
	`hasAttachment` boolean NOT NULL DEFAULT false,
	`isRead` boolean NOT NULL DEFAULT false,
	`isStarred` boolean NOT NULL DEFAULT false,
	`internalDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_messages_id` PRIMARY KEY(`id`),
	CONSTRAINT `email_messages_gmailMessageId_unique` UNIQUE(`gmailMessageId`)
);
